name: security-scan-sast

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *" # Sets Semgrep to scan every day at 1:30 UTC

jobs:
  scan:
    uses: verygood-ops/cicd-shared/.github/workflows/security-scan-sast.yaml@security-scan-sast-v1
    with:
      uses_maven: false
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
